build: false

environment:
  matrix:
    - PYTHON: "C:\\Python27"
      BITS: "32bit"
    - PYTHON: "C:\\Python27-x64"
      BITS: "64bit"
    - PYTHON: "C:\\Python36"
      BITS: "32bit"
    - PYTHON: "C:\\Python36-x64"
      BITS: "64bit"

branches:
  only:
    - master

init:
  - "ECHO %PYTHON%"

install:
  - "SET PATH=%PYTHON%;%PYTHON%\\Scripts;%PATH%"
  - "pip install -r requirements.txt"
  - "pip install flake8"

test_script:
  - "flake8 ./vss-ransom-restore/"
  - "./build.bat nopause"

artifacts:
  - path: "dist/vss-ransom-restore_32bit.exe"
    name: "vss-ransom-restore_32bit.exe"

  - path: "dist/vss-ransom-restore_64bit.exe"
    name: "vss-ransom-restore_64bit.exe"
